# Generated by Django 5.2.8 on 2025-11-13 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_price', models.DecimalField(decimal_places=2, help_text='Current gold price per unit', max_digits=10)),
                ('silver_price', models.DecimalField(decimal_places=2, help_text='Current silver price per unit', max_digits=10)),
                ('effective_date', models.DateTimeField(auto_now_add=True, help_text='Date when these prices became effective')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Category name', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of category name', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Banner name for identification', max_length=200)),
                ('image', models.ImageField(help_text='Banner image', upload_to='banners/')),
                ('active', models.BooleanField(default=True, help_text='Whether this banner is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['active'], name='adminapp_ba_active_9524af_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Unique product identifier', max_length=50, unique=True)),
                ('product_name', models.CharField(help_text='Product name', max_length=300)),
                ('size', models.CharField(blank=True, help_text='Product size (e.g., S, M, L, XL)', max_length=100, null=True)),
                ('image1', models.ImageField(help_text='Primary product image', upload_to='products/')),
                ('image2', models.ImageField(blank=True, help_text='Secondary product image', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='adminapp.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_id'], name='adminapp_pr_product_e460be_idx'), models.Index(fields=['category', 'product_name'], name='adminapp_pr_categor_9525bb_idx')],
            },
        ),
    ]
